### ISSUE TITLE
Nothing happend when to start the program

### ISSUE THREAD

**Issue by riparuk** [CyberTimon/powerpointer#14] opened 2024-10-02 17:22 UTC
Hi, 
I tried start by `python3 app.py` but nothing work.
idk how to run, am I missing something?
<img width="466" alt="Screenshot 2024-10-03 at 00 22 05" src="https://github.com/user-attachments/assets/b780fe22-79cc-471b-a3e4-35e70d88a6ec">

**Comment by CyberTimon** [comment] 2024-10-02 19:42
Hello

That looks very strange. There must be at least one error.

Have you tried installing all the pip packages? Does the error still occur?
Can you run other Python projects without any problems?

Kind regards,
Timon

**Comment by riparuk** [comment] 2024-10-02 21:11
<img width="491" alt="Screenshot 2024-10-03 at 04 04 05" src="https://github.com/user-attachments/assets/2a52ffd0-96cd-415f-9bb7-146ce028fb47">
All Packages already installed.

Before that, when I want to start after put the api key in the `app.py` it ask for OPENAI_API_KEY set as env variable
<img width="1096" alt="Screenshot 2024-10-03 at 04 06 58" src="https://github.com/user-attachments/assets/16fc760e-f35b-465e-aeeb-0c1f7f85d1e4">

After the env var setup, when I try to run again, it's like nothing happened
<img width="428" alt="Screenshot 2024-10-03 at 04 10 51" src="https://github.com/user-attachments/assets/85d0d0cf-620e-4c96-a1c6-6c2b851d3a99">

**Comment by riparuk** [comment] 2024-10-02 21:17
nvm, now its work by using `flask` or `python -m flask` command according to flask docs
<img width="399" alt="Screenshot 2024-10-03 at 04 15 12" src="https://github.com/user-attachments/assets/643b943a-84f7-476c-af15-b54bcadc9477">

**Comment by CyberTimon** [comment] 2024-10-04 06:46
Great, so it works now? It's still pretty weird that it doesn't work when running the normal Python file, but it's hard to debug since I can't reproduce it.

**Comment by riparuk** [comment] 2024-10-04 18:17
Yeah its work now. maybe because of library updates, etc. Actually, you can still run normal python files by adding this inat the end of the file : 
```python
if __name__ == '__main__':
    # debug=True in the run() parameter if you want to debug
    app.run()
```

and also I have mentioned before that even though the api key has been added in app.py, in the terminal I still ask for OPENAI_API_KEY set as env variable, it fixed with simply by changing it to : 
```python
import openai
client = openai.OpenAI(api_key='api-key')
``` 
I'll make a pull request, hope it can help.

**Comment by CyberTimon** [comment] 2024-10-04 20:42
Thank you! I've merged the PR 👍

**Closed as completed by CyberTimon** 2024-10-04 20:42 UTC
